name: Build ffmpeg
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        abi: [ "arm64-v8a" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Setup the environment
        run: |
          sudo pip3 install meson==1.2.2
          sudo apt-get install nasm ninja-build gtk-doc-tools
      - name: Executing the script
        run: |
          export ANDROID_SDK_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_NDK
          ./ffmpeg-android-maker.sh -all-free -x264 -all-bsd -fdk-aac -android=21 -abis=${{ matrix.abi }}

      - name: upload ffmpeg
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg
          path: build/ffmpeg/arm64-v8a/bin/*
